# Generated by Django 6.0.2 on 2026-03-14 22:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('py', 'Python'), ('ja', 'Java'), ('js', 'JavaScript'), ('c++', 'C++'), ('c#', 'C#'), ('an', 'Android')], verbose_name='Курс')),
                ('course_num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Номер курса')),
                ('start_date', models.DateField(null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url-slug')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name', 'course_num'],
                'unique_together': {('name', 'course_num')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)], verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], null=True, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото или оставьте пустым для авто-уточки', null=True, upload_to='students/photos/', verbose_name='Фотография')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url-slug')),
                ('courses', models.ManyToManyField(blank=True, related_name='enrolled_students', to='main.course', verbose_name='Посещаемые курсы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('date', models.DateField(null=True, verbose_name='Дата оценки')),
                ('date_add', models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('date_update', models.DateField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url-slug')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='main.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grades', to='main.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)], verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], null=True, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото или оставьте пустым для авто-лисички', null=True, upload_to='teachers/photos/', verbose_name='Фотография')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url-slug')),
                ('courses', models.ManyToManyField(blank=True, related_name='taught_by', to='main.course', verbose_name='Преподаваемые курсы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['surname'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['surname'], name='main_studen_surname_307540_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['surname'], name='main_teache_surname_500b08_idx'),
        ),
    ]
