# Generated by Django 6.0.2 on 2026-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('py', 'Python'), ('ja', 'Java'), ('js', 'JavaScript'), ('cpp', 'C++'), ('csh', 'C#'), ('an', 'Android')], verbose_name='Курс'),
        ),
    ]
