# Generated by Django 6.0.2 on 2026-03-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_alter_student_courses_alter_teacher_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Пригласительный код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Действитилен до')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Использован пользователем')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пригласительный код',
                'verbose_name_plural': 'Пригласительные коды',
                'ordering': ['-created_at'],
            },
        ),
    ]
